//
// Created by 许昊文 on 2018/11/12.
//

#ifndef ML_GRIDENGINE_EXECUTOR_MACROS_H
#define ML_GRIDENGINE_EXECUTOR_MACROS_H

#define MLGridEngineExecutor_API
#define DEFINE_NON_PRIMITIVE_PROPERTY(TYPE, NAME) \
  private: \
    TYPE _##NAME; \
  public: \
    inline TYPE& NAME() { return _##NAME; } \
    inline TYPE const& NAME() const { return _##NAME; }

#define ML_GRIDENGINE_ENV_PREFIX "ML_GRIDENGINE_"
#define ML_GRIDENGINE_DEFAULT_BUFFER_SIZE (4UL * 1024 * 1024)
#define ML_GRIDENGINE_CLIENT_READ_MAX_TIMEOUT_SECONDS (300)
#define ML_GRIDENGINE_CLIENT_READ_DEFAULT_TIMEOUT_SECONDS (60)
#ifndef ML_GRIDENGINE_KILL_PROGRAM_FIRST_WAIT_SECONDS
# define ML_GRIDENGINE_KILL_PROGRAM_FIRST_WAIT_SECONDS (10)
#endif
#ifndef ML_GRIDENGINE_KILL_PROGRAM_SECOND_WAIT_SECONDS
# define ML_GRIDENGINE_KILL_PROGRAM_SECOND_WAIT_SECONDS (20)
#endif
#ifndef ML_GRIDENGINE_KILL_PROGRAM_FINAL_WAIT_SECONDS
# define ML_GRIDENGINE_KILL_PROGRAM_FINAL_WAIT_SECONDS (60)
#endif

#endif //ML_GRIDENGINE_EXECUTOR_MACROS_H
